export interface DefaultRule {
  pattern: string;
  main_category: string;
  sub_category?: string;
  match_type: 'keyword';
  priority: number;
}

export const DEFAULT_RULES: DefaultRule[] = [
  // === 饮食 ===
  { pattern: '美团外卖', main_category: '饮食', sub_category: '外卖', match_type: 'keyword', priority: 100 },
  { pattern: '饿了么', main_category: '饮食', sub_category: '外卖', match_type: 'keyword', priority: 100 },
  { pattern: '美团', main_category: '饮食', match_type: 'keyword', priority: 50 },
  { pattern: '外卖', main_category: '饮食', sub_category: '外卖', match_type: 'keyword', priority: 50 },
  { pattern: '餐厅', main_category: '饮食', sub_category: '晚餐', match_type: 'keyword', priority: 50 },
  { pattern: '饭店', main_category: '饮食', sub_category: '晚餐', match_type: 'keyword', priority: 50 },
  { pattern: '小吃', main_category: '饮食', sub_category: '零食', match_type: 'keyword', priority: 50 },
  { pattern: '肯德基', main_category: '饮食', sub_category: '午餐', match_type: 'keyword', priority: 100 },
  { pattern: '麦当劳', main_category: '饮食', sub_category: '午餐', match_type: 'keyword', priority: 100 },
  { pattern: '必胜客', main_category: '饮食', sub_category: '晚餐', match_type: 'keyword', priority: 100 },
  { pattern: '海底捞', main_category: '饮食', sub_category: '聚餐', match_type: 'keyword', priority: 100 },
  { pattern: '火锅', main_category: '饮食', sub_category: '聚餐', match_type: 'keyword', priority: 50 },
  { pattern: '烧烤', main_category: '饮食', sub_category: '聚餐', match_type: 'keyword', priority: 50 },
  { pattern: '奶茶', main_category: '饮食', sub_category: '饮品', match_type: 'keyword', priority: 50 },
  { pattern: '咖啡', main_category: '饮食', sub_category: '饮品', match_type: 'keyword', priority: 50 },
  { pattern: '星巴克', main_category: '饮食', sub_category: '饮品', match_type: 'keyword', priority: 100 },
  { pattern: '瑞幸', main_category: '饮食', sub_category: '饮品', match_type: 'keyword', priority: 100 },
  { pattern: '喜茶', main_category: '饮食', sub_category: '饮品', match_type: 'keyword', priority: 100 },
  { pattern: '奈雪', main_category: '饮食', sub_category: '饮品', match_type: 'keyword', priority: 100 },
  { pattern: '蜜雪冰城', main_category: '饮食', sub_category: '饮品', match_type: 'keyword', priority: 100 },
  { pattern: '茶百道', main_category: '饮食', sub_category: '饮品', match_type: 'keyword', priority: 100 },
  { pattern: '霸王茶姬', main_category: '饮食', sub_category: '饮品', match_type: 'keyword', priority: 100 },
  { pattern: '一点点', main_category: '饮食', sub_category: '饮品', match_type: 'keyword', priority: 100 },
  { pattern: 'CoCo', main_category: '饮食', sub_category: '饮品', match_type: 'keyword', priority: 100 },
  { pattern: '超市', main_category: '饮食', sub_category: '买菜', match_type: 'keyword', priority: 30 },
  { pattern: '买菜', main_category: '饮食', sub_category: '买菜', match_type: 'keyword', priority: 50 },
  { pattern: '水果', main_category: '饮食', sub_category: '零食', match_type: 'keyword', priority: 50 },
  { pattern: '面包', main_category: '饮食', sub_category: '早餐', match_type: 'keyword', priority: 50 },
  { pattern: '早餐', main_category: '饮食', sub_category: '早餐', match_type: 'keyword', priority: 50 },
  { pattern: '盒马', main_category: '饮食', sub_category: '买菜', match_type: 'keyword', priority: 80 },
  { pattern: '叮咚', main_category: '饮食', sub_category: '买菜', match_type: 'keyword', priority: 80 },
  { pattern: '永辉', main_category: '饮食', sub_category: '买菜', match_type: 'keyword', priority: 80 },
  { pattern: '大润发', main_category: '饮食', sub_category: '买菜', match_type: 'keyword', priority: 80 },
  { pattern: '山姆', main_category: '饮食', sub_category: '买菜', match_type: 'keyword', priority: 80 },

  // === 购物 ===
  { pattern: '淘宝', main_category: '购物', match_type: 'keyword', priority: 80 },
  { pattern: '京东', main_category: '购物', sub_category: '数码', match_type: 'keyword', priority: 80 },
  { pattern: '拼多多', main_category: '购物', match_type: 'keyword', priority: 80 },
  { pattern: '天猫', main_category: '购物', match_type: 'keyword', priority: 80 },
  { pattern: '唯品会', main_category: '购物', sub_category: '服装', match_type: 'keyword', priority: 80 },
  { pattern: '得物', main_category: '购物', sub_category: '服装', match_type: 'keyword', priority: 80 },
  { pattern: '闲鱼', main_category: '购物', match_type: 'keyword', priority: 80 },
  { pattern: '当当', main_category: '购物', sub_category: '书籍', match_type: 'keyword', priority: 80 },
  { pattern: '泡泡玛特', main_category: '购物', sub_category: '潮玩', match_type: 'keyword', priority: 100 },
  { pattern: '盲盒', main_category: '购物', sub_category: '潮玩', match_type: 'keyword', priority: 80 },
  { pattern: '优衣库', main_category: '购物', sub_category: '服装', match_type: 'keyword', priority: 80 },
  { pattern: 'ZARA', main_category: '购物', sub_category: '服装', match_type: 'keyword', priority: 80 },
  { pattern: 'H&M', main_category: '购物', sub_category: '服装', match_type: 'keyword', priority: 80 },
  { pattern: '迪卡侬', main_category: '购物', sub_category: '服装', match_type: 'keyword', priority: 80 },
  { pattern: '名创优品', main_category: '购物', sub_category: '日用品', match_type: 'keyword', priority: 80 },
  { pattern: '屈臣氏', main_category: '购物', sub_category: '美妆', match_type: 'keyword', priority: 80 },
  { pattern: '丝芙兰', main_category: '购物', sub_category: '美妆', match_type: 'keyword', priority: 80 },
  { pattern: '苹果', main_category: '购物', sub_category: '数码', match_type: 'keyword', priority: 50 },
  { pattern: '华为', main_category: '购物', sub_category: '数码', match_type: 'keyword', priority: 50 },
  { pattern: '小米', main_category: '购物', sub_category: '数码', match_type: 'keyword', priority: 50 },
  { pattern: '宜家', main_category: '购物', sub_category: '家居', match_type: 'keyword', priority: 80 },
  { pattern: 'Nike', main_category: '购物', sub_category: '服装', match_type: 'keyword', priority: 80 },
  { pattern: 'Adidas', main_category: '购物', sub_category: '服装', match_type: 'keyword', priority: 80 },

  // === 交通 ===
  { pattern: '滴滴出行', main_category: '交通', sub_category: '打车', match_type: 'keyword', priority: 100 },
  { pattern: '滴滴', main_category: '交通', sub_category: '打车', match_type: 'keyword', priority: 100 },
  { pattern: '曹操出行', main_category: '交通', sub_category: '打车', match_type: 'keyword', priority: 100 },
  { pattern: 'T3出行', main_category: '交通', sub_category: '打车', match_type: 'keyword', priority: 100 },
  { pattern: '花小猪', main_category: '交通', sub_category: '打车', match_type: 'keyword', priority: 100 },
  { pattern: '高德打车', main_category: '交通', sub_category: '打车', match_type: 'keyword', priority: 100 },
  { pattern: '地铁', main_category: '交通', sub_category: '地铁', match_type: 'keyword', priority: 80 },
  { pattern: '公交', main_category: '交通', sub_category: '公交', match_type: 'keyword', priority: 80 },
  { pattern: '加油站', main_category: '交通', sub_category: '加油', match_type: 'keyword', priority: 80 },
  { pattern: '中石化', main_category: '交通', sub_category: '加油', match_type: 'keyword', priority: 80 },
  { pattern: '中石油', main_category: '交通', sub_category: '加油', match_type: 'keyword', priority: 80 },
  { pattern: '停车', main_category: '交通', sub_category: '停车', match_type: 'keyword', priority: 80 },
  { pattern: '高速', main_category: '交通', sub_category: '停车', match_type: 'keyword', priority: 50 },
  { pattern: 'ETC', main_category: '交通', match_type: 'keyword', priority: 80 },
  { pattern: '12306', main_category: '交通', sub_category: '火车', match_type: 'keyword', priority: 100 },
  { pattern: '火车票', main_category: '交通', sub_category: '火车', match_type: 'keyword', priority: 100 },
  { pattern: '机票', main_category: '交通', sub_category: '飞机', match_type: 'keyword', priority: 100 },
  { pattern: '航空', main_category: '交通', sub_category: '飞机', match_type: 'keyword', priority: 80 },
  { pattern: '哈啰', main_category: '交通', match_type: 'keyword', priority: 80 },
  { pattern: '青桔', main_category: '交通', match_type: 'keyword', priority: 80 },
  { pattern: '美团单车', main_category: '交通', match_type: 'keyword', priority: 80 },

  // === 住房 ===
  { pattern: '房租', main_category: '住房', sub_category: '房租', match_type: 'keyword', priority: 100 },
  { pattern: '物业', main_category: '住房', match_type: 'keyword', priority: 100 },
  { pattern: '水电费', main_category: '住房', sub_category: '水电', match_type: 'keyword', priority: 100 },
  { pattern: '电费', main_category: '住房', sub_category: '水电', match_type: 'keyword', priority: 100 },
  { pattern: '水费', main_category: '住房', sub_category: '水电', match_type: 'keyword', priority: 100 },
  { pattern: '燃气费', main_category: '住房', sub_category: '燃气', match_type: 'keyword', priority: 100 },
  { pattern: '燃气', main_category: '住房', sub_category: '燃气', match_type: 'keyword', priority: 80 },
  { pattern: '煤气', main_category: '住房', sub_category: '燃气', match_type: 'keyword', priority: 80 },
  { pattern: '宽带', main_category: '住房', sub_category: '宽带', match_type: 'keyword', priority: 100 },
  { pattern: '网费', main_category: '住房', sub_category: '宽带', match_type: 'keyword', priority: 80 },
  { pattern: '电信', main_category: '住房', sub_category: '宽带', match_type: 'keyword', priority: 50 },
  { pattern: '联通', main_category: '住房', sub_category: '宽带', match_type: 'keyword', priority: 50 },
  { pattern: '移动', main_category: '住房', sub_category: '宽带', match_type: 'keyword', priority: 30 },
  { pattern: '维修', main_category: '住房', sub_category: '维修', match_type: 'keyword', priority: 50 },
  { pattern: '装修', main_category: '住房', sub_category: '家装', match_type: 'keyword', priority: 80 },
  { pattern: '房产', main_category: '住房', match_type: 'keyword', priority: 50 },

  // === 娱乐 ===
  { pattern: '电影', main_category: '娱乐', sub_category: '电影', match_type: 'keyword', priority: 50 },
  { pattern: '电影院', main_category: '娱乐', sub_category: '电影', match_type: 'keyword', priority: 80 },
  { pattern: '淘票票', main_category: '娱乐', sub_category: '电影', match_type: 'keyword', priority: 100 },
  { pattern: '猫眼', main_category: '娱乐', sub_category: '电影', match_type: 'keyword', priority: 100 },
  { pattern: 'KTV', main_category: '娱乐', sub_category: 'KTV', match_type: 'keyword', priority: 100 },
  { pattern: '网吧', main_category: '娱乐', sub_category: '游戏', match_type: 'keyword', priority: 80 },
  { pattern: '游戏充值', main_category: '娱乐', sub_category: '游戏', match_type: 'keyword', priority: 100 },
  { pattern: '王者荣耀', main_category: '娱乐', sub_category: '游戏', match_type: 'keyword', priority: 100 },
  { pattern: '原神', main_category: '娱乐', sub_category: '游戏', match_type: 'keyword', priority: 100 },
  { pattern: '和平精英', main_category: '娱乐', sub_category: '游戏', match_type: 'keyword', priority: 100 },
  { pattern: '剧本杀', main_category: '娱乐', match_type: 'keyword', priority: 100 },
  { pattern: '密室逃脱', main_category: '娱乐', match_type: 'keyword', priority: 100 },
  { pattern: '抖音', main_category: '娱乐', sub_category: '订阅服务', match_type: 'keyword', priority: 100 },
  { pattern: '快手', main_category: '娱乐', sub_category: '订阅服务', match_type: 'keyword', priority: 100 },
  { pattern: 'B站', main_category: '娱乐', sub_category: '订阅服务', match_type: 'keyword', priority: 100 },
  { pattern: '哔哩哔哩', main_category: '娱乐', sub_category: '订阅服务', match_type: 'keyword', priority: 100 },
  { pattern: '爱奇艺', main_category: '娱乐', sub_category: '订阅服务', match_type: 'keyword', priority: 100 },
  { pattern: '腾讯视频', main_category: '娱乐', sub_category: '订阅服务', match_type: 'keyword', priority: 100 },
  { pattern: '优酷', main_category: '娱乐', sub_category: '订阅服务', match_type: 'keyword', priority: 100 },
  { pattern: '网易云音乐', main_category: '娱乐', sub_category: '订阅服务', match_type: 'keyword', priority: 100 },
  { pattern: 'QQ音乐', main_category: '娱乐', sub_category: '订阅服务', match_type: 'keyword', priority: 100 },
  { pattern: 'Spotify', main_category: '娱乐', sub_category: '订阅服务', match_type: 'keyword', priority: 100 },
  { pattern: 'Apple Music', main_category: '娱乐', sub_category: '订阅服务', match_type: 'keyword', priority: 100 },
  { pattern: '迪士尼', main_category: '娱乐', sub_category: '旅行', match_type: 'keyword', priority: 80 },
  { pattern: '欢乐谷', main_category: '娱乐', sub_category: '旅行', match_type: 'keyword', priority: 80 },
  { pattern: '景区', main_category: '娱乐', sub_category: '旅行', match_type: 'keyword', priority: 80 },
  { pattern: '酒店', main_category: '娱乐', sub_category: '旅行', match_type: 'keyword', priority: 50 },
  { pattern: '民宿', main_category: '娱乐', sub_category: '旅行', match_type: 'keyword', priority: 80 },
  { pattern: '携程', main_category: '娱乐', sub_category: '旅行', match_type: 'keyword', priority: 80 },
  { pattern: '飞猪', main_category: '娱乐', sub_category: '旅行', match_type: 'keyword', priority: 80 },
  { pattern: '健身', main_category: '娱乐', sub_category: '运动', match_type: 'keyword', priority: 80 },
  { pattern: 'Keep', main_category: '娱乐', sub_category: '运动', match_type: 'keyword', priority: 100 },
  { pattern: '游泳', main_category: '娱乐', sub_category: '运动', match_type: 'keyword', priority: 80 },

  // === 医疗 ===
  { pattern: '医院', main_category: '医疗', sub_category: '医院', match_type: 'keyword', priority: 80 },
  { pattern: '药房', main_category: '医疗', sub_category: '药房', match_type: 'keyword', priority: 80 },
  { pattern: '药店', main_category: '医疗', sub_category: '药房', match_type: 'keyword', priority: 80 },
  { pattern: '药', main_category: '医疗', match_type: 'keyword', priority: 20 },
  { pattern: '挂号', main_category: '医疗', sub_category: '医院', match_type: 'keyword', priority: 100 },
  { pattern: '门诊', main_category: '医疗', sub_category: '医院', match_type: 'keyword', priority: 80 },
  { pattern: '体检', main_category: '医疗', sub_category: '体检', match_type: 'keyword', priority: 100 },
  { pattern: '牙科', main_category: '医疗', sub_category: '牙科', match_type: 'keyword', priority: 100 },
  { pattern: '牙医', main_category: '医疗', sub_category: '牙科', match_type: 'keyword', priority: 100 },
  { pattern: '诊所', main_category: '医疗', match_type: 'keyword', priority: 80 },

  // === 教育 ===
  { pattern: '学费', main_category: '教育', sub_category: '学费', match_type: 'keyword', priority: 100 },
  { pattern: '课程', main_category: '教育', sub_category: '培训', match_type: 'keyword', priority: 80 },
  { pattern: '培训班', main_category: '教育', sub_category: '培训', match_type: 'keyword', priority: 100 },
  { pattern: '培训', main_category: '教育', sub_category: '培训', match_type: 'keyword', priority: 80 },
  { pattern: '教材', main_category: '教育', sub_category: '教材', match_type: 'keyword', priority: 80 },
  { pattern: '考试', main_category: '教育', sub_category: '考试', match_type: 'keyword', priority: 80 },
  { pattern: '学而思', main_category: '教育', sub_category: '培训', match_type: 'keyword', priority: 100 },
  { pattern: '新东方', main_category: '教育', sub_category: '培训', match_type: 'keyword', priority: 100 },
  { pattern: '网易公开课', main_category: '教育', sub_category: '培训', match_type: 'keyword', priority: 100 },
  { pattern: '得到', main_category: '教育', sub_category: '培训', match_type: 'keyword', priority: 100 },
  { pattern: '知乎盐选', main_category: '教育', sub_category: '培训', match_type: 'keyword', priority: 100 },

  // === 投资 ===
  { pattern: '基金', main_category: '投资', sub_category: '基金', match_type: 'keyword', priority: 80 },
  { pattern: '股票', main_category: '投资', sub_category: '股票', match_type: 'keyword', priority: 80 },
  { pattern: '理财', main_category: '投资', match_type: 'keyword', priority: 80 },
  { pattern: '定投', main_category: '投资', sub_category: '基金', match_type: 'keyword', priority: 100 },
  { pattern: '余额宝', main_category: '投资', sub_category: '基金', match_type: 'keyword', priority: 80 },
  { pattern: '基金定投', main_category: '投资', sub_category: '基金', match_type: 'keyword', priority: 100 },
  { pattern: '证券', main_category: '投资', sub_category: '股票', match_type: 'keyword', priority: 80 },
  { pattern: '保险', main_category: '投资', sub_category: '保险', match_type: 'keyword', priority: 80 },
  { pattern: '寿险', main_category: '投资', sub_category: '保险', match_type: 'keyword', priority: 100 },
  { pattern: '车险', main_category: '投资', sub_category: '保险', match_type: 'keyword', priority: 100 },
  { pattern: '医疗险', main_category: '投资', sub_category: '保险', match_type: 'keyword', priority: 100 },
  { pattern: '平安保险', main_category: '投资', sub_category: '保险', match_type: 'keyword', priority: 100 },
  { pattern: '人寿', main_category: '投资', sub_category: '保险', match_type: 'keyword', priority: 100 },

  // === 人情往来 ===
  { pattern: '微信红包', main_category: '人情往来', sub_category: '红包', match_type: 'keyword', priority: 100 },
  { pattern: '红包', main_category: '人情往来', sub_category: '红包', match_type: 'keyword', priority: 80 },
  { pattern: '转账', main_category: '人情往来', sub_category: '红包', match_type: 'keyword', priority: 30 },
  { pattern: '礼金', main_category: '人情往来', match_type: 'keyword', priority: 100 },
  { pattern: '随礼', main_category: '人情往来', match_type: 'keyword', priority: 100 },
  { pattern: '结婚', main_category: '人情往来', sub_category: '婚礼', match_type: 'keyword', priority: 80 },
  { pattern: '生日', main_category: '人情往来', sub_category: '礼物', match_type: 'keyword', priority: 50 },
  { pattern: '礼物', main_category: '人情往来', sub_category: '礼物', match_type: 'keyword', priority: 50 },
  { pattern: '鲜花', main_category: '人情往来', sub_category: '礼物', match_type: 'keyword', priority: 80 },
  { pattern: '捐款', main_category: '人情往来', sub_category: '捐赠', match_type: 'keyword', priority: 100 },
  { pattern: '捐赠', main_category: '人情往来', sub_category: '捐赠', match_type: 'keyword', priority: 100 },
  { pattern: '慈善', main_category: '人情往来', sub_category: '捐赠', match_type: 'keyword', priority: 100 },

  // === 其他 ===
  { pattern: '快递', main_category: '其他', sub_category: '快递', match_type: 'keyword', priority: 50 },
  { pattern: '顺丰', main_category: '其他', sub_category: '快递', match_type: 'keyword', priority: 80 },
  { pattern: '中通', main_category: '其他', sub_category: '快递', match_type: 'keyword', priority: 80 },
  { pattern: '圆通', main_category: '其他', sub_category: '快递', match_type: 'keyword', priority: 80 },
  { pattern: '韵达', main_category: '其他', sub_category: '快递', match_type: 'keyword', priority: 80 },
  { pattern: '话费', main_category: '其他', sub_category: '通讯', match_type: 'keyword', priority: 100 },
  { pattern: '充值', main_category: '其他', sub_category: '通讯', match_type: 'keyword', priority: 50 },
  { pattern: '手续费', main_category: '其他', sub_category: '手续费', match_type: 'keyword', priority: 80 },
  { pattern: '服务费', main_category: '其他', sub_category: '手续费', match_type: 'keyword', priority: 50 },
];
